# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.java.home=/home/shiina/.local/share/PrismLauncher/java/java-runtime-epsilon

# Fabric Properties
minecraft_version=26.3
loader_version=0.19.5

# Mod Properties
mod_version=1.0.0+26.3
maven_group=com.autoutils
archives_base_name=autoutils

# Dependencies
fabric_version=0.161.0+26.3
cloth_config_version=26.3.159
mod_menu_version=20.0.2
